[tool.poetry]
name = "salinity"
version = "0.0.1"
description = ""
authors = ["Gediminas Zlatkus <gediminas.zlatkus@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pyyaml = "^5.1"
jinja2 = "^2.10"
salt = "^2019.2"
tornado = "^6.0"
msgpack = "^0.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
