[tool.poetry]
name = "salinity"
version = "0.0.1"
description = ""
authors = ["Gediminas Zlatkus <gediminas.zlatkus@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
