[tool.poetry]
name = "slskit"
version = "2022.10.0"
authors = ["Gediminas Zlatkus <gediminas.zlatkus@gmail.com>"]
description = "Tools for checking Salt state validity"
readme = "README.md"
homepage = "https://github.com/gediminasz/slskit"
repository = "https://github.com/gediminasz/slskit"
keywords = ["salt", "saltstack", "sls"]
classifiers = ["Topic :: Software Development :: Quality Assurance"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"
colorlog = "^6.7.0"
funcy = "^1.17"
jsonschema = "^4.17.3"
salt = ">=3004.0"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
gitpython = "^3.1.30"
mypy = "^0.991"
pylint = "^2.15.10"
pytest = "^7.2.0"
pytest-snapshot = "^0.9.0"
types-pyyaml = "^6.0.12.2"

[tool.poetry.scripts]
slskit = 'slskit:run_module'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
