name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        salt-version: ["3004.*", "3005.*"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run checks
        run: |
          pip install poetry
          poetry install
          poetry run pip install --upgrade 'salt==${{ matrix.salt-version }}'
          poetry run salt --versions
          make check
