name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        salt-version: ["3006.*", "3007.*"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run checks
        run: |
          pip install --upgrade pip poetry
          pip --version
          poetry --version
          poetry add 'salt==${{ matrix.salt-version }}'
          poetry install
          poetry run salt --versions
          make all
